import React, { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowRight, Bot, BriefcaseBusiness, Building2, CalendarDays, ChevronRight, CircleDollarSign, Coins, CreditCard, Home, Landmark, LayoutDashboard, Menu, MessageSquareText, Moon, PiggyBank, ReceiptText, Search, Settings, ShieldCheck, Sparkles, Target, TrendingUp, Users, WalletCards, X } from "lucide-react";
import "./demo.css";

const fmt = (value, compact = false) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: compact ? 0 : 0, notation: compact ? "compact" : "standard" }).format(value);
const pct = value => `${Number(value).toFixed(0)}%`;

const incomeMix = [
  { name: "W-2 employment", value: 15250, color: "#667eea", labor: true },
  { name: "Contracting", value: 7367, color: "#25a18e", labor: true },
  { name: "Operating businesses", value: 2980, color: "#d68c45", labor: false },
  { name: "Rental / ADU", value: 1550, color: "#a56cc1", labor: false },
  { name: "Investments", value: 640, color: "#c6a34f", labor: false },
];

const monthly = [
  { month: "Mar", income: 24200, spending: 17040, wealth: 684000 }, { month: "Apr", income: 25150, spending: 17880, wealth: 693500 },
  { month: "May", income: 24800, spending: 16520, wealth: 704000 }, { month: "Jun", income: 26740, spending: 18120, wealth: 716900 },
  { month: "Jul", income: 27110, spending: 17690, wealth: 728400 }, { month: "Aug", income: 27787, spending: 18362, wealth: 742650 },
];

const businesses = [
  { name: "Northstar Automation", type: "Professional consulting · S-Corp", stage: "Operating", revenue: 7367, expenses: 1480, profit: 5887, capital: 8000, distributions: 2800, cash: 23100, roi: 73.6, trend: 12, accent: "mint" },
  { name: "Canyon Goods Co.", type: "Wholesale & product operations", stage: "Growing", revenue: 4250, expenses: 2710, profit: 1540, capital: 18500, distributions: 600, cash: 9800, roi: 8.3, trend: 18, accent: "blue" },
  { name: "Juniper Field Labs", type: "Developing digital venture", stage: "Validation", revenue: 420, expenses: 760, profit: -340, capital: 6200, distributions: 0, cash: 3100, roi: -5.5, trend: 34, accent: "amber" },
];

const debts = [
  { name: "Primary mortgage", balance: 318400, rate: 3.25, payment: 2260, priority: "Maintain" },
  { name: "HELOC / legacy consolidation", balance: 112600, rate: 8.35, payment: 1350, priority: "Accelerate" },
  { name: "Auto loan", balance: 21900, rate: 5.49, payment: 525, priority: "Next" },
  { name: "Credit cards", balance: 8400, rate: 20.9, payment: 900, priority: "Immediate" },
];

const wealth = [
  { name: "Retirement", value: 286500, color: "#d4af57" }, { name: "Taxable investments", value: 118400, color: "#efcf79" },
  { name: "Real-estate equity", value: 392000, color: "#8d7440" }, { name: "Business equity", value: 88400, color: "#6d8f82" },
  { name: "Cash reserves", value: 82450, color: "#71829f" }, { name: "Liabilities", value: -225100, color: "#9a6570" },
];

const transactions = [
  ["Aug 26", "Northstar client payment", "Contracting income", 7225], ["Aug 25", "Vanguard automatic investment", "Long-term wealth", -2800],
  ["Aug 24", "Canyon Goods marketplace", "Business revenue", 1480], ["Aug 23", "Mountain View Mortgage", "Housing", -2260],
  ["Aug 22", "AFCU credit card payment", "Transfer", -900], ["Aug 21", "ADU rent", "Rental income", 1550],
  ["Aug 20", "Northstar payroll", "S-Corp wages", 3200], ["Aug 19", "Costco", "Groceries & household", -284],
];

const prompts = ["How are we doing this month?", "What should I prioritize next?", "How dependent are we on my labor?", "How much can I safely invest?"];
const answers = {
  "How are we doing this month?": { title: "You’re building momentum this month.", body: "Household income is $27,787 and spending is $18,362, leaving $9,425 of free cash flow. Net worth increased about $14,250, driven by contributions, market growth, and business profit.", actions: ["Reserve $2,400 for estimated taxes", "Direct $1,500 to the high-rate card balance", "Keep $3,800 available for investing and business reinvestment"] },
  "What should I prioritize next?": { title: "Eliminate the 20.9% card balance first.", body: "Your reserves already cover 4.5 months. Paying the card creates a risk-free return that exceeds expected portfolio returns, while preserving enough liquidity for taxes and business operations.", actions: ["Pay an extra $1,500 this month", "Keep the HELOC on its current accelerated schedule", "Review Juniper’s validation milestone before adding capital"] },
  "How dependent are we on my labor?": { title: "81% of income still depends on personal labor.", body: "W-2 and contracting produce $22,617 of this month’s $27,787. Operator-independent business, rental, and investment income cover 28% of current household spending—up from 21% six months ago.", actions: ["Systematize Northstar delivery", "Improve Canyon Goods contribution margin", "Continue funding diversified long-term assets"] },
  "How much can I safely invest?": { title: "About $3,800 is available this month.", body: "After normal spending, estimated taxes, minimum debt payments, and maintaining the reserve floor, you have approximately $3,800 of deployable capital.", actions: ["$2,300 to diversified investments", "$1,000 to Canyon inventory with proven sell-through", "$500 held for Juniper validation—not scaling"] },
};

const nav = [
  ["command", "Command Center", LayoutDashboard], ["advisor", "GPT Financial Advisor", MessageSquareText], ["household", "Household", Users], ["income", "Income", CircleDollarSign],
  ["transactions", "Transactions", ReceiptText], ["budget", "Budget & Cash Flow", WalletCards], ["debt", "Debt", CreditCard], ["networth", "Net Worth", TrendingUp],
  ["contracting", "Contracting / S-Corp", BriefcaseBusiness], ["business", "Business Portfolio", Building2], ["taxes", "Taxes", Landmark], ["goals", "Goals", Target],
  ["wealth", "Retirement & Wealth", PiggyBank], ["settings", "Settings", Settings],
];

function Metric({ label, value, detail, tone }) { return <article className={`demo-metric ${tone || ""}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
function Progress({ value, gold = false }) { return <div className={`progress ${gold ? "gold" : ""}`}><i style={{ width: `${Math.min(value, 100)}%` }} /></div>; }
function SectionTitle({ eyebrow, title, aside }) { return <div className="section-title"><div><span>{eyebrow}</span><h2>{title}</h2></div>{aside}</div>; }

function Advisor({ compact = false }) {
  const [messages, setMessages] = useState(compact ? [] : [{ role: "assistant", content: "Good morning. I’ve reviewed your household cash flow, businesses, debt, and long-term wealth plan. What would you like to understand?" }]);
  const [input, setInput] = useState("");
  const ask = question => { const q = question || input.trim(); if (!q) return; const match = Object.keys(answers).find(key => q.toLowerCase().includes(key.replace("?", "").toLowerCase().split(" ").slice(1).join(" "))) || prompts[Math.floor(Math.random() * prompts.length)]; const answer = answers[match]; setMessages(current => [...current, { role: "user", content: q }, { role: "assistant", ...answer }]); setInput(""); };
  return <section className={`advisor ${compact ? "compact" : "full"}`}>
    <div className="advisor-head"><div className="ai-mark"><Sparkles size={18}/></div><div><strong>FCC Advisor</strong><span>Demo intelligence · all data is fictional</span></div><i>Ready</i></div>
    {!compact && <div className="chat-stream">{messages.map((message, index) => message.role === "user" ? <div className="bubble user" key={index}>{message.content}</div> : <div className="bubble assistant" key={index}><Bot size={18}/><div><strong>{message.title}</strong><p>{message.content || message.body}</p>{message.actions && <ul>{message.actions.map(action => <li key={action}>{action}</li>)}</ul>}<small>Planning estimate · not tax or investment advice</small></div></div>)}</div>}
    <div className="prompt-row">{prompts.slice(0, compact ? 3 : 4).map(prompt => <button key={prompt} onClick={() => ask(prompt)}>{prompt}</button>)}</div>
    <form onSubmit={event => { event.preventDefault(); ask(); }}><Sparkles size={18}/><input value={input} onChange={event => setInput(event.target.value)} placeholder="Ask about cash flow, taxes, debt, businesses, or wealth…"/><button>Ask <ArrowRight size={16}/></button></form>
  </section>;
}

function CommandCenter({ go }) { return <>
  <div className="welcome"><div><span className="overline">Wednesday, August 27</span><h1>Good morning, Taylor.</h1><p>Your financial system is healthy. Free cash flow and income diversification both improved this month.</p></div><div className="confidence"><ShieldCheck/><span><strong>Demo workspace</strong>Fictional household data</span></div></div>
  <section className="metric-grid"><Metric label="Monthly income" value="$27,787" detail="↑ 8.4% vs. 6-mo avg" tone="positive"/><Metric label="Monthly spending" value="$18,362" detail="66% of income"/><Metric label="Free cash flow" value="$9,425" detail="33.9% margin" tone="positive"/><Metric label="Net worth" value="$742,650" detail="↑ $14,250 this month" tone="gold"/><Metric label="Liquid reserves" value="$82,450" detail="4.5 months covered"/><Metric label="Total debt" value="$461,300" detail="↓ $3,410 this month"/></section>
  <Advisor compact />
  <section className="split-grid"><article className="demo-panel income-panel"><SectionTitle eyebrow="Income diversification" title="Where your income comes from" aside={<button onClick={() => go("income")}>Explore income <ChevronRight size={15}/></button>}/><div className="income-content"><ResponsiveContainer width="45%" height={220}><PieChart><Pie data={incomeMix} dataKey="value" innerRadius={58} outerRadius={88} paddingAngle={3}>{incomeMix.map(row => <Cell key={row.name} fill={row.color}/>)}</Pie><Tooltip formatter={value => fmt(value)}/></PieChart></ResponsiveContainer><div className="legend-list">{incomeMix.map(row => <div key={row.name}><i style={{ background: row.color }}/><span>{row.name}<small>{pct(row.value / 27787 * 100)} of income</small></span><strong>{fmt(row.value)}</strong></div>)}</div></div><div className="labor-callout"><span><strong>81%</strong> dependent on personal labor</span><Progress value={81}/><small>Goal: below 50% · down 3 points over 6 months</small></div></article>
  <article className="demo-panel"><SectionTitle eyebrow="Cash flow" title="Six-month operating trend"/><ResponsiveContainer width="100%" height={225}><BarChart data={monthly}><CartesianGrid stroke="#e8ebf2" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={value => fmt(value)}/><Bar dataKey="income" fill="#5369d8" radius={[5,5,0,0]}/><Bar dataKey="spending" fill="#d9deeb" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer><div className="chart-key"><span><i className="indigo"/>Income</span><span><i/>Spending</span><strong>Aug margin 33.9%</strong></div></article></section>
  <section className="demo-panel focus"><SectionTitle eyebrow="This month" title="CFO focus"/><div className="focus-grid"><button onClick={() => go("debt")}><span className="focus-icon coral"><CreditCard/></span><span><strong>Remove expensive debt</strong><small>Credit card APR is 20.9%</small></span><b>$1,500 extra</b><ChevronRight/></button><button onClick={() => go("business")}><span className="focus-icon green"><Building2/></span><span><strong>Back proven economics</strong><small>Canyon Goods margin is improving</small></span><b>$1,000 capacity</b><ChevronRight/></button><button onClick={() => go("wealth")}><span className="focus-icon gold"><PiggyBank/></span><span><strong>Compound long-term wealth</strong><small>Investment rate is 22.4%</small></span><b>$2,300 planned</b><ChevronRight/></button></div></section>
  </>; }

function BusinessPortfolio() { return <><PageIntro kicker="Business portfolio" title="Businesses should earn their place in the portfolio." text="Compare economic value creation, capital efficiency, and operator dependence across every venture."/><div className="business-summary"><Metric label="Portfolio revenue" value="$12,037" detail="This month"/><Metric label="Portfolio profit" value="$7,087" detail="58.9% blended margin" tone="positive"/><Metric label="Capital invested" value="$32,700" detail="Across three ventures"/><Metric label="Cash available" value="$36,000" detail="Entity operating cash"/></div><div className="business-grid">{businesses.map(b => <article className={`business-card ${b.accent}`} key={b.name}><div className="business-top"><div><span>{b.type}</span><h3>{b.name}</h3></div><i>{b.stage}</i></div><div className="business-kpis"><span>Revenue<strong>{fmt(b.revenue)}</strong></span><span>Expenses<strong>{fmt(b.expenses)}</strong></span><span>Profit<strong className={b.profit < 0 ? "negative" : ""}>{fmt(b.profit)}</strong></span></div><div className="business-row"><span>Owner capital <b>{fmt(b.capital)}</b></span><span>Distributions <b>{fmt(b.distributions)}</b></span><span>Cash <b>{fmt(b.cash)}</b></span></div><div className="roi"><span><strong>{b.roi}%</strong> monthly return on capital*</span><em>↑ {b.trend}% revenue trend</em></div><button>Review business economics <ChevronRight/></button></article>)}</div><p className="footnote">*Planning signal based on current-period profit and tracked owner capital; not an annualized investment return.</p></>; }

function Contracting() { const flow=[{name:"Client revenue",value:7367},{name:"Operating expenses",value:1480},{name:"Owner wages",value:3200},{name:"Est. payroll taxes",value:490},{name:"Remaining profit",value:2197}]; return <><PageIntro kicker="Contracting / S-Corp" title="Northstar Automation" text="Platform configuration and automation development · $85/hour · ~20 hours/week · C2C through an S-Corp"/><div className="business-summary"><Metric label="Monthly revenue" value="$7,367" detail="86.7 billable hours"/><Metric label="Operating profit" value="$5,887" detail="79.9% before owner comp" tone="positive"/><Metric label="Owner compensation" value="$3,200" detail="Planning assumption"/><Metric label="Reinvestment capacity" value="$2,197" detail="Before estimated income tax" tone="gold"/></div><section className="contract-grid"><article className="demo-panel"><SectionTitle eyebrow="Monthly economics" title="From revenue to retained profit"/><div className="waterfall">{flow.map((row,i)=><div key={row.name}><span>{row.name}</span><i className={i===0||i===4?"positive":""} style={{width:`${Math.max(row.value/7367*100,12)}%`}}/><strong>{i>0&&i<4?"−":""}{fmt(row.value)}</strong></div>)}</div></article><article className="demo-panel planning-note"><span className="focus-icon green"><BriefcaseBusiness/></span><h3>Compensation planning checkpoint</h3><p>Owner wages should be reviewed against role, hours, market compensation, and current guidance—not selected solely to minimize payroll taxes.</p><div><span>Est. payroll taxes<strong>$490/mo</strong></span><span>Est. quarterly tax reserve<strong>$6,600</strong></span></div><small>Educational estimate only. Review with a qualified tax professional.</small></article></section></>; }

function Wealth() { const coverage=28; return <div className="wealth-view"><PageIntro kicker="Retirement & long-term wealth" title="Turn earned income into durable freedom." text="Build assets and operator-independent income until work becomes a choice, not a requirement."/><div className="wealth-hero"><div><span>Long-term net worth</span><strong>$742,650</strong><small>↑ $114,200 over the last 12 months</small></div><div><span>Financial Independence Income Coverage</span><strong>{coverage}%</strong><Progress value={coverage} gold/><small>$5,170 recurring / $18,362 household spending · goal 100%+</small></div></div><div className="wealth-grid"><article className="demo-panel dark-gold"><SectionTitle eyebrow="Projected wealth" title="$2.18M by 2036"/><ResponsiveContainer width="100%" height={260}><AreaChart data={[{y:"2026",v:743},{y:"2028",v:940},{y:"2030",v:1190},{y:"2032",v:1475},{y:"2034",v:1805},{y:"2036",v:2180}]}><defs><linearGradient id="goldfill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#e5c66f" stopOpacity=".45"/><stop offset="1" stopColor="#e5c66f" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="y" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={v=>fmt(v*1000)}/><Area dataKey="v" stroke="#e5c66f" strokeWidth={3} fill="url(#goldfill)"/></AreaChart></ResponsiveContainer><small>Illustrative 7% portfolio growth, current contributions, and debt trajectory.</small></article><article className="demo-panel"><SectionTitle eyebrow="Wealth composition" title="Assets working for you"/><div className="wealth-list">{wealth.filter(w=>w.value>0).map(w=><div key={w.name}><i style={{background:w.color}}/><span>{w.name}</span><strong>{fmt(w.value)}</strong><small>{pct(w.value/967750*100)}</small></div>)}</div></article></div><div className="business-summary"><Metric label="Annual contributions" value="$68,400" detail="Retirement + taxable"/><Metric label="Investment rate" value="22.4%" detail="Of gross household income" tone="gold"/><Metric label="Personal labor dependence" value="81%" detail="Target below 50%"/><Metric label="FI coverage" value="28%" detail="Up 7 points in 12 months" tone="gold"/></div></div>; }

function Debt() { return <><PageIntro kicker="Debt strategy" title="Direct every extra dollar with intent." text="Protect liquidity, remove high-cost balances, then accelerate the debt that most constrains cash flow."/><div className="business-summary"><Metric label="Total debt" value="$461,300" detail="↓ $3,410 this month"/><Metric label="Weighted rate" value="5.6%" detail="Across four liabilities"/><Metric label="Monthly payments" value="$5,035" detail="27.4% of spending"/><Metric label="Interest avoided" value="$4,180" detail="Next 12 months with plan" tone="positive"/></div><section className="demo-panel"><SectionTitle eyebrow="Recommended order" title="Debt payoff plan"/><div className="debt-table"><div className="table-head"><span>Liability</span><span>Balance</span><span>Rate</span><span>Payment</span><span>Strategy</span></div>{debts.map((d,i)=><div key={d.name}><span><i>{i+1}</i><strong>{d.name}</strong></span><span>{fmt(d.balance)}</span><span className={d.rate>8?"negative":""}>{d.rate}%</span><span>{fmt(d.payment)}</span><b className={d.priority.toLowerCase()}>{d.priority}</b></div>)}</div></section></>; }

function Transactions() { const [query,setQuery]=useState(""); const rows=transactions.filter(t=>t.join(" ").toLowerCase().includes(query.toLowerCase())); return <><PageIntro kicker="Transactions" title="A clean, normalized household ledger." text="Search the seeded demo activity or open the full data workspace for imports, categorization rules, receipts, and reconciliation."/><section className="demo-panel transaction-panel"><div className="transaction-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search transactions"/></label><a href="?workspace=1">Open full data workspace <ArrowRight/></a></div><div className="demo-transactions">{rows.map((t,i)=><div key={i}><span>{t[0]}</span><span><strong>{t[1]}</strong><small>{t[2]}</small></span><b className={t[3]>0?"positive":""}>{t[3]>0?"+":""}{fmt(t[3])}</b></div>)}</div></section></>; }

function Taxes() { return <><PageIntro kicker="Tax planning" title="One household, several tax lanes." text="Keep wages, pass-through profit, business costs, payroll, retirement contributions, and estimates visibly separate."/><div className="tax-banner"><ShieldCheck/><div><strong>2026 projected household tax reserve: $58,400</strong><span>Planning estimate based on fictional demo assumptions—not a tax return or tax advice.</span></div></div><section className="tax-grid">{[["W-2 compensation","$183,000","Federal and state withholding tracked through payroll"],["S-Corp owner wages","$38,400","Payroll withholding plus employer/employee payroll taxes"],["S-Corp pass-through profit","$26,364","Estimated quarterly payments modeled separately"],["Operating business profit","$14,400","Net of ordinary tracked business expenses"],["Retirement contributions","$42,000","Employee and employer contributions assumed"],["Family-business payroll","$6,000","Documented, age-appropriate services workflow"]].map(r=><article key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><small>{r[2]}</small></article>)}</section></>; }

function Generic({ view }) { const data={household:["Household","Your shared financial foundation.","Track reserves, spending, protection, and the decisions that connect every wealth engine."],income:["Income","Diversification is moving in the right direction.","See what comes from employment, contracting, businesses, rental operations, and invested assets."],budget:["Budget & cash flow","Give every surplus dollar a job.","Current spending is 66% of income, creating a healthy $9,425 monthly operating surplus."],networth:["Net worth","Measure the whole system, not one account.","Assets, liabilities, business equity, real estate, and reserves combine into a $742,650 household position."],goals:["Goals","Translate priorities into funded outcomes.","Debt freedom, education, business growth, and financial independence compete for the same capital—sequence them deliberately."],settings:["Demo settings","Safe by design for the presentation.","This beta uses fictional data and requires no Teller token, bank credential, or production secret."]}[view]; return <><PageIntro kicker={data[0]} title={data[1]} text={data[2]}/><section className="metric-grid"><Metric label="Monthly income" value="$27,787" detail="Five income sources"/><Metric label="Free cash flow" value="$9,425" detail="33.9% margin" tone="positive"/><Metric label="Reserve coverage" value="4.5 months" detail="$82,450 liquid"/><Metric label="FI income coverage" value="28%" detail="Goal 100%+" tone="gold"/></section><section className="demo-panel"><SectionTitle eyebrow="Six-month view" title="The household is compounding steadily"/><ResponsiveContainer width="100%" height={300}><LineChart data={monthly}><CartesianGrid stroke="#edf0f5" vertical={false}/><XAxis dataKey="month"/><YAxis hide/><Tooltip formatter={value=>fmt(value)}/><Line dataKey="wealth" stroke="#5369d8" strokeWidth={3}/></LineChart></ResponsiveContainer></section></>; }

function PageIntro({ kicker,title,text }) { return <div className="page-intro"><span>{kicker}</span><h1>{title}</h1><p>{text}</p></div>; }

export default function DemoApp() {
  const [view,setView]=useState("command"); const [mobile,setMobile]=useState(false); const [dark,setDark]=useState(false);
  const title=nav.find(item=>item[0]===view)?.[1];
  const content=useMemo(()=>{if(view==="command")return <CommandCenter go={setView}/>;if(view==="advisor")return <><PageIntro kicker="GPT Financial Advisor" title="Ask the whole financial system." text="Contextual demo responses connect household cash flow, entities, taxes, debt, and long-term wealth."/><Advisor/></>;if(view==="business")return <BusinessPortfolio/>;if(view==="contracting")return <Contracting/>;if(view==="wealth")return <Wealth/>;if(view==="debt")return <Debt/>;if(view==="transactions")return <Transactions/>;if(view==="taxes")return <Taxes/>;return <Generic view={view}/>},[view]);
  return <div className={`demo-app ${dark?"dark":""}`}><aside className={mobile?"open":""}><div className="brand"><div><Coins/></div><span><strong>Financial</strong><small>Command Center</small></span><button onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([id,label,Icon],index)=><React.Fragment key={id}>{index===0&&<small>OVERVIEW</small>}{index===2&&<small>HOUSEHOLD</small>}{index===8&&<small>WEALTH ENGINES</small>}<button className={view===id?"active":""} onClick={()=>{setView(id);setMobile(false)}}><Icon/>{label}{id==="wealth"&&<i>GOLD</i>}</button></React.Fragment>)}</nav><div className="sidebar-foot"><div className="avatar">TF</div><span><strong>Taylor Family</strong><small>Demo household</small></span></div></aside><main><header className="demo-header"><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><span>{title}</span><small>Demo data · Aug 2026</small></div><div className="header-actions"><button><Search/></button><button onClick={()=>setDark(!dark)}><Moon/></button><a href="?workspace=1"><Settings/> Data workspace</a></div></header><div className="demo-content">{content}</div></main>{mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>}</div>;
}
