import React, { useState } from "react";
import { Activity, AlertTriangle, ArrowRight, BarChart3, Bell, Building2, Check, CheckCircle2, ChevronRight, Clock3, Database, Eye, FileCheck2, FileSignature, Filter, KeyRound, Link2, LockKeyhole, MessageSquareText, Monitor, Moon, RefreshCw, Search, ShieldCheck, Sparkles, Unplug, UserCheck, Users } from "lucide-react";
import "./platform.css";

const households = [
  { name:"Taylor Family", advisor:"Morgan Lee", status:"Review ready", opportunity:"High-cost debt", updated:"12 min ago", tone:"ready", score:88 },
  { name:"Ortiz Household", advisor:"Morgan Lee", status:"Needs attention", opportunity:"Reserve coverage", updated:"2 hr ago", tone:"attention", score:64 },
  { name:"Chen Family", advisor:"Avery Kim", status:"Waiting on client", opportunity:"Account refresh", updated:"Yesterday", tone:"waiting", score:76 },
  { name:"Williams Household", advisor:"Avery Kim", status:"Review ready", opportunity:"Tax reserve", updated:"Yesterday", tone:"ready", score:91 },
];
const roleMatrix = [
  ["Firm owner","Firm administration, billing, policies, and all assigned households","2 users"],
  ["Advisor","Assigned households, analysis review, and client presentation","5 users"],
  ["Associate","Draft preparation; no final client approval","3 users"],
  ["Client owner","Household data, members, acknowledgments, and shared analyses","24 users"],
  ["Household member","Views explicitly permitted by the client owner","18 users"],
];
const events = [
  ["Morgan Lee","Approved an opportunity analysis","Taylor Family · High-cost debt","12 min ago"],
  ["Jordan Taylor","Acknowledged the educational-use disclosure","Taylor Family · Investment capacity","18 min ago"],
  ["System","Recalculated household metrics","Taylor Family · 42 verified inputs","22 min ago"],
];

function Intro({eyebrow,title,text,right}) { return <div className="platform-intro"><div><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{right}</div>; }
function Stat({label,value,note,tone=""}) { return <article className={`platform-stat ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }
function Heading({eyebrow,title,action}) { return <div className="platform-heading"><div><span>{eyebrow}</span><h2>{title}</h2></div>{action}</div>; }
function useSavedState(key,initial){const [value,setValue]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))??initial}catch{return initial}});const save=next=>{setValue(next);localStorage.setItem(key,JSON.stringify(next))};return [value,save]}

export function AdvisorConsole() {
  const [selected,setSelected]=useState(households[0]);
  return <div className="platform-view"><Intro eyebrow="Advisor operating console" title="Start with the households that need judgment." text="Review system-detected opportunities, prepare client conversations, and preserve a defensible approval trail." right={<button className="platform-primary"><Users/> Add household</button>}/>
    <div className="platform-stats"><Stat label="Households" value="24" note="18 active this month"/><Stat label="Reviews ready" value="7" note="3 newly calculated" tone="good"/><Stat label="Needs attention" value="4" note="Data or cash-flow exceptions" tone="warn"/><Stat label="Awaiting client" value="5" note="Requests or acknowledgments"/></div>
    <section className="console-grid"><article className="platform-card"><Heading eyebrow="Client book" title="Household work queue" action={<div className="platform-tools"><button><Filter/></button><label><Search/><input placeholder="Search households"/></label></div>}/><div className="client-table"><div className="client-head"><span>Household</span><span>Status</span><span>Opportunity</span><span>Updated</span><span/></div>{households.map(row=><button className={selected.name===row.name?"selected":""} onClick={()=>setSelected(row)} key={row.name}><span><i>{row.name.split(" ").map(v=>v[0]).join("").slice(0,2)}</i><b>{row.name}<small>{row.advisor}</small></b></span><em className={row.tone}>{row.status}</em><span>{row.opportunity}</span><span>{row.updated}</span><ChevronRight/></button>)}</div></article>
      <article className="platform-card review-card"><span>Selected household</span><h2>{selected.name}</h2><small>Assigned to {selected.advisor}</small><div className="readiness"><strong>{selected.score}</strong><span>Financial system readiness</span></div><div className="opportunity-box"><span><Sparkles/> Opportunity awaiting review</span><strong>{selected.opportunity}</strong><p>The system found a planning condition that may warrant discussion. Review its inputs, assumptions, and educational framing before sharing.</p><button>Open review workspace <ArrowRight/></button></div><div className="review-buttons"><button><MessageSquareText/> Prepare meeting agenda</button><button><FileCheck2/> Request client information</button></div></article></section>
    <section className="platform-card activity-card"><Heading eyebrow="Audit stream" title="Recent firm activity" action={<button className="platform-link">View full audit log</button>}/>{events.map((row,index)=><div className="activity-row" key={index}><i><Activity/></i><span><strong>{row[0]}</strong> {row[1]}<small>{row[2]}</small></span><time>{row[3]}</time></div>)}</section>
  </div>;
}

export function AccessControl() {
  return <div className="platform-view"><Intro eyebrow="Firm & household access" title="Every person sees only what their role requires." text="Firm boundaries, household assignments, and sensitive actions are explicit, reviewable, and recorded." right={<button className="platform-primary"><UserCheck/> Invite user</button>}/>
    <div className="security-banner"><ShieldCheck/><span><strong>Northstar Advisory · isolated firm workspace</strong><small>24 households · 10 firm users · MFA policy enforced</small></span><em>All controls healthy</em></div>
    <section className="access-grid"><article className="platform-card"><Heading eyebrow="Tenant boundary" title="Organization structure"/><div className="tenant-tree"><div><i><Building2/></i><span><strong>Northstar Advisory</strong><small>Firm tenant · FCC-ORG-1048</small></span><b>Owner</b></div><section><div><i><Users/></i><span><strong>Advisory team</strong><small>10 members · 3 firm roles</small></span></div><div><i><LockKeyhole/></i><span><strong>24 client households</strong><small>Strictly isolated data spaces</small></span></div><div className="house-node"><i>TF</i><span><strong>Taylor Family</strong><small>2 members · Morgan Lee assigned</small></span><b>Client owner</b></div></section></div></article>
      <article className="platform-card"><Heading eyebrow="Security policies" title="Access requirements"/>{[["Multi-factor authentication","Required for all firm users"],["Advisor household assignment","Required before access"],["Sensitive export approval","Firm owner approval"],["Session timeout","30 minutes"],["Client data download","Disabled for associates"]].map(row=><div className="policy-row" key={row[0]}><i><Check/></i><span><strong>{row[0]}</strong><small>{row[1]}</small></span><em>Enforced</em></div>)}</article></section>
    <section className="platform-card role-card"><Heading eyebrow="Least-privilege roles" title="Role and permission model" action={<button className="platform-link">Manage custom roles</button>}/><div className="role-head"><span>Role</span><span>Effective access</span><span>Assigned</span><span/></div>{roleMatrix.map(row=><div className="role-row" key={row[0]}><strong>{row[0]}</strong><span>{row[1]}</span><b>{row[2]}</b><ChevronRight/></div>)}</section>
    <section className="platform-card audit-card"><Heading eyebrow="Security audit" title="Recent access events"/>{[["Morgan Lee","Viewed Taylor Family cash-flow analysis","Assigned advisor","10:42 AM",false],["Jordan Taylor","Viewed investment-capacity opportunity","Disclosure acknowledged","10:36 AM",false],["Avery Kim","Requested Williams Household export","Owner approval required","Yesterday",true]].map((row,index)=><div key={index}><i className={row[4]?"warn":""}>{row[4]?<AlertTriangle/>:<CheckCircle2/>}</i><span><strong>{row[0]}</strong><small>{row[1]}</small></span><em>{row[2]}</em><time>{row[3]}</time></div>)}</section>
  </div>;
}

export function AIGovernance() {
  const [traceOpen,setTraceOpen]=useState(true);
  return <div className="platform-view"><Intro eyebrow="Controlled intelligence" title="The system calculates. AI explains. A human decides." text="Every opportunity preserves its inputs, formula, assumptions, language policy, review state, and client acknowledgment." right={<span className="model-status"><i/> Policy engine active</span>}/>
    <section className="governance-flow">{[["Calculate","Deterministic engine","done"],["Explain","Constrained framing","done"],["Advisor review","Human judgment","current"],["Present","Approved + acknowledged",""]].map((row,index)=><React.Fragment key={row[0]}><article className={row[2]}><i>{index+1}</i><span><strong>{row[0]}</strong><small>{row[1]}</small></span>{row[2]==="done"?<CheckCircle2/>:row[2]==="current"?<Clock3/>:<LockKeyhole/>}</article>{index<3&&<ChevronRight/>}</React.Fragment>)}</section>
    <section className="governance-grid"><article className="platform-card analysis-review"><div className="analysis-title"><div><span><Sparkles/> Opportunity draft</span><h2>High-cost debt may be constraining deployable cash flow</h2><p>Taylor Family · Generated 10:31 AM · Policy FCC-OPP-2.1</p></div><em>Awaiting advisor review</em></div><div className="language-check"><ShieldCheck/><span><strong>Language policy passed</strong><small>Conditional educational framing; no instruction to transact, guarantee, product recommendation, or claim of optimality.</small></span><button>View checks</button></div><div className="draft-copy"><span>Client-ready draft</span><p>The household’s revolving card balance carries a materially higher rate than its other tracked liabilities. This may be an area to discuss when comparing liquidity needs, debt reduction, and additional investing. Several allocation scenarios are available for review.</p></div><div className="analysis-actions"><button className="return">Return for revision</button><button>Edit explanation</button><button className="approve"><Check/> Approve for client</button></div></article>
      <article className="platform-card trace-card"><button onClick={()=>setTraceOpen(!traceOpen)}><span><strong>Calculation receipt</strong><small>FCC-DEBT-004 · formula v2.3.1</small></span><ChevronRight className={traceOpen?"open":""}/></button>{traceOpen&&<div>{[["Revolving balance","$8,400","AMEX · refreshed Aug 27"],["Annual percentage rate","20.90%","Client-confirmed assumption"],["Liquid reserves","$82,450","3 connected accounts"],["Reserve floor","$61,200","4.0 × essential spending"]].map(row=><section key={row[0]}><span>{row[0]}</span><strong>{row[1]}</strong><small>{row[2]}</small></section>)}<pre>{"rate_gap = 20.90% − 7.00% model return\navailable_above_floor = $21,250\nsignal = HIGH_COST_DEBT_REVIEW"}</pre><div className="receipt-meta"><span>Calculated <b>Aug 27 · 10:31 AM</b></span><span>Input snapshot <b>42 records · locked</b></span><span>Release <b>FCC 0.9.4</b></span></div><button><Eye/> Inspect all 42 inputs</button></div>}</article></section>
    <section className="platform-card evaluation-card"><Heading eyebrow="Model quality" title="Release evaluation suite" action={<span className="eval-pass"><CheckCircle2/> 148 / 150 passed</span>}/><div className="eval-grid"><Stat label="Calculation fidelity" value="100%" note="46 deterministic cases" tone="good"/><Stat label="Tenant isolation" value="100%" note="32 adversarial cases" tone="good"/><Stat label="Advice-language policy" value="98.6%" note="2 blocked for review" tone="warn"/><Stat label="Citation completeness" value="100%" note="24 household cases" tone="good"/></div><div className="blocked-note"><AlertTriangle/><span><strong>Two outputs blocked from client presentation</strong><small>Language implied a single optimal action. Both remain quarantined for policy review.</small></span><button>Review blocked cases <ArrowRight/></button></div></section>
  </div>;
}

export function DataConnections({persona="advisor"}) {
  const [connected,setConnected]=useSavedState("fcc-demo-connected",true); const [sharing,setSharing]=useSavedState("fcc-demo-advisor-sharing",true); const [refreshing,setRefreshing]=useState(false); const [notice,setNotice]=useState("");
  const refresh=()=>{setRefreshing(true);setNotice("");setTimeout(()=>{setRefreshing(false);setNotice("Demo refresh completed · 14 records reconciled · no raw credentials stored")},700)};
  const revoke=()=>{setConnected(false);setSharing(false);setNotice("Connection revoked. Future synchronization and advisor sharing are stopped.")};
  return <div className="platform-view"><Intro eyebrow="Teller bank connection" title="Connect and manage household financial accounts." text="Use Teller to add read-only balances and transactions. The household controls what is connected, who can see it, and when access ends." right={!connected?<button className="platform-primary" onClick={()=>{setConnected(true);setNotice("Demo Teller connection completed. No real credentials were requested.")}}><Link2/> Connect with Teller</button>:<span className="model-status"><i/> Teller demo connected</span>}/>
    <div className="security-banner"><ShieldCheck/><span><strong>Protected server-side connection model</strong><small>Signed provider events · encrypted credentials · seven-day reconciliation overlap</small></span><em>Design target</em></div>
    <section className="connection-grid"><article className="platform-card"><Heading eyebrow="Connected through Teller" title="Mountain West Credit Union" action={<em className={connected?"status-live":"status-off"}>{connected?"Connected":"Disconnected"}</em>}/>{connected?<><div className="connection-account"><i><Database/></i><span><strong>Checking •• 1842 + 2 accounts</strong><small>Transactions and balances · read-only</small></span><b>Updated 18 min ago</b></div><div className="freshness"><span>Data freshness</span><strong>Current</strong><i><b style={{width:"92%"}}></b></i></div><div className="connection-actions"><button onClick={refresh} disabled={refreshing}><RefreshCw className={refreshing?"spin":""}/>{refreshing?"Refreshing…":"Refresh Teller data"}</button><button className="danger-lite" onClick={revoke}><Unplug/>Disconnect Teller</button></div></>:<div className="empty-connection"><Unplug/><strong>No bank accounts connected</strong><p>Connect with Teller to add read-only transactions and balances.</p><button className="platform-primary" onClick={()=>{setConnected(true);setNotice("Demo Teller connection completed. A production connection would now open Teller Connect.")}}><Link2/>Connect with Teller</button></div>}</article>
      <article className="platform-card consent-card"><Heading eyebrow="Authorization receipt" title="Consent FCC-CNS-1048"/><div className="consent-state"><CheckCircle2/><span><strong>{connected?"Active authorization":"Authorization revoked"}</strong><small>{connected?"Granted Aug 12, 2026 · review Aug 12, 2027":"Synchronization disabled"}</small></span></div>{[["Purpose","Household cash-flow and planning analysis"],["Data scope","Balances + transactions; no payment initiation"],["Provider","Teller · provider adapter v1"],["Disclosure","FCC Financial Data Authorization v1.2"]].map(row=><div className="consent-row" key={row[0]}><span>{row[0]}</span><strong>{row[1]}</strong></div>)}</article></section>
    <section className="platform-card share-card"><Heading eyebrow="Advisor access" title="Household sharing controls"/><div><span><strong>Share financial workspace with Morgan Lee</strong><small>Assigned advisor · Northstar Advisory</small></span><button className={`toggle ${sharing?"on":""}`} aria-label="Toggle advisor sharing" onClick={()=>{const next=!sharing;setSharing(next);setNotice(next?"Advisor access enabled and recorded.":"Advisor access removed and recorded.")}}><i/></button></div><p>{persona==="advisor"?"This control is shown as the household would see it. Advisors cannot grant themselves access.":"Turning this off immediately removes the advisor’s household access without deleting your copy of the data."}</p></section>
    {notice&&<div className="inline-success"><CheckCircle2/>{notice}</div>}
    <section className="data-principles">{[["Collect less","No account/routing numbers in analytics"],["Refresh intelligently","Events trigger background reconciliation"],["Delete deliberately","Revocation starts the retention workflow"],["Prove access","Consent and sensitive actions are versioned"]].map(row=><article key={row[0]}><strong>{row[0]}</strong><span>{row[1]}</span></article>)}</section>
  </div>
}

export function SettingsPage({go,persona,dark,setDark}){
  const [notices,setNotices]=useSavedState("fcc-demo-notices",true); const [weekly,setWeekly]=useSavedState("fcc-demo-weekly",true);
  return <div className="platform-view"><Intro eyebrow="Workspace settings" title="Configure your Financial Command Center." text="Manage bank connections, household access, appearance, notifications, and the boundaries of this demo workspace."/>
    <section className="settings-grid"><article className="platform-card settings-card featured"><i><Database/></i><div><span>Financial data</span><h2>Teller bank connection</h2><p>Add or manage read-only bank accounts, review data freshness, and revoke access.</p><button className="platform-primary" onClick={()=>go("connections")}><Link2/> Open bank connections</button></div></article>
      <article className="platform-card settings-card"><i><Users/></i><div><span>People & access</span><h2>{persona==="advisor"?"Firm and household access":"Household sharing"}</h2><p>{persona==="advisor"?"Manage roles, household assignments, and access policies.":"Choose which advisor can view this household."}</p><button onClick={()=>go(persona==="advisor"?"access":"connections")}>Manage access <ChevronRight/></button></div></article>
      <article className="platform-card settings-card"><i>{dark?<Moon/>:<Monitor/>}</i><div><span>Appearance</span><h2>{dark?"Dark theme":"Light theme"}</h2><p>Choose the display that is most comfortable for reviewing financial information.</p><button onClick={()=>setDark(!dark)}>Switch to {dark?"light":"dark"} <ChevronRight/></button></div></article>
      <article className="platform-card settings-card"><i><Bell/></i><div><span>Notifications</span><h2>Review reminders</h2><div className="setting-toggle"><label>Important data issues<small>Connection failures and stale information</small></label><button className={`toggle ${notices?"on":""}`} onClick={()=>setNotices(!notices)}><i/></button></div><div className="setting-toggle"><label>Weekly summary<small>Cash flow and opportunities to review</small></label><button className={`toggle ${weekly?"on":""}`} onClick={()=>setWeekly(!weekly)}><i/></button></div></div></article>
    </section>
    <section className="platform-card workspace-boundary"><Heading eyebrow="About this workspace" title="Presentation beta"/><div><ShieldCheck/><span><strong>Fictional data only</strong><small>This public demonstration does not accept real bank credentials. “Connect with Teller” demonstrates the intended consent flow; production connectivity requires the secured server environment.</small></span></div></section>
  </div>
}

export function LaunchCenter(){
  const [model,setModel]=useSavedState("fcc-demo-launch-model","sponsored"); const models=[{id:"referral",name:"Referral",note:"Platform contracts with each household",fit:"Lowest complexity"},{id:"sponsored",name:"Firm-sponsored",note:"Firm licenses a co-branded client workspace",fit:"Recommended launch"},{id:"white",name:"Full white-label",note:"Firm rebrands and resells the platform",fit:"Later phase"}];
  const checklist=[["Design-partner agreement","Ready for counsel"],["Master services agreement","Draft required"],["Data processing + security addendum","Draft required"],["Privacy policy + end-user terms","Draft required"],["Subprocessor register","Structure ready"],["Incident notice + deletion schedule","Control owner assigned"]];
  return <div className="platform-view"><Intro eyebrow="Commercial launch center" title="Choose the operating model before choosing the sales motion." text="Ownership, disclosures, support, data responsibilities, and branding remain visible as the platform moves from design partner to paid beta." right={<button className="platform-primary"><FileSignature/> Export launch brief</button>}/>
    <section className="model-picker">{models.map(row=><button className={model===row.id?"selected":""} onClick={()=>setModel(row.id)} key={row.id}><span>{row.fit}</span><strong>{row.name}</strong><small>{row.note}</small>{model===row.id&&<CheckCircle2/>}</button>)}</section>
    <section className="launch-grid"><article className="platform-card"><Heading eyebrow="Selected structure" title={models.find(row=>row.id===model).name}/><div className="responsibility-grid"><span>Client relationship<strong>{model==="referral"?"FCC + household":"Advisory firm"}</strong></span><span>Platform operation<strong>Financial Command Center</strong></span><span>Professional judgment<strong>Advisor / coach</strong></span><span>Mandatory disclosures<strong>Platform controlled</strong></span></div><div className="launch-note"><ShieldCheck/><span><strong>Claims guardrail</strong><small>No guaranteed outcomes, optimal-action claims, or editable removal of required disclosures.</small></span></div></article><article className="platform-card"><Heading eyebrow="Paid beta package" title="Contract readiness"/>{checklist.map((row,index)=><div className="checklist-row" key={row[0]}><i className={index===0?"done":""}>{index===0?<Check/>:index+1}</i><span><strong>{row[0]}</strong><small>{row[1]}</small></span></div>)}</article></section>
    <div className="not-certified"><AlertTriangle/><span><strong>Readiness boundary</strong><small>This beta demonstrates the required operating controls. It is not a legal opinion, security certification, or authorization to process production financial data.</small></span></div>
  </div>
}

export function Measurement(){
  const funnel=[{label:"Firm setup",value:12},{label:"First household",value:10},{label:"Data connected",value:8},{label:"First review",value:7},{label:"Client viewed",value:5}];
  const metrics=[["Advisor activation","58%","7 of 12 firms completed a first review","up"],["Median preparation time","18 min","Baseline: 47 min","up"],["Opportunity approval","64%","22% edited · 14% rejected",""],["Sync success","98.4%","1.6% needs reconnection","up"],["Support burden","3.1","Tickets / 100 households",""],["Client helpfulness","4.4 / 5","After acknowledged views","up"]];
  return <div className="platform-view"><Intro eyebrow="Pilot measurement" title="Measure workflow value before making outcome claims." text="The pilot tracks activation, advisor efficiency, analysis quality, reliability, and commercial learning without sending financial details to general analytics." right={<span className="model-status"><i/> Event schema v1.0</span>}/>
    <div className="platform-stats"><Stat label="Tracked events" value="18" note="12 client · 6 server authoritative"/><Stat label="Event health" value="99.6%" note="Validated in last 24 hours" tone="good"/><Stat label="Sensitive fields blocked" value="42" note="Descriptions, balances, PII" tone="good"/><Stat label="Pilot households" value="86" note="Across 12 design partners"/></div>
    <section className="measurement-grid"><article className="platform-card"><Heading eyebrow="Activation funnel" title="From firm setup to client value"/>{funnel.map((row,index)=><div className="funnel-row" key={row.label}><span>{row.label}</span><i style={{width:`${row.value/12*100}%`}}/><strong>{row.value}</strong>{index<funnel.length-1&&<small>{Math.round(funnel[index+1].value/row.value*100)}%</small>}</div>)}</article><article className="platform-card"><Heading eyebrow="Instrumentation" title="What is now observable"/>{[["Identity","Organization, role, household, cohort"],["Journey","Onboarding, connect, review, acknowledge"],["Quality","Approve, edit, reject, policy block"],["Reliability","Freshness, sync, errors, latency"],["Commercial","Conversion, retention, expansion"]].map(row=><div className="observable-row" key={row[0]}><CheckCircle2/><span><strong>{row[0]}</strong><small>{row[1]}</small></span></div>)}</article></section>
    <section className="platform-card"><Heading eyebrow="Pilot scorecard" title="Decision-grade measures" action={<button className="platform-link"><BarChart3/> Metric definitions</button>}/><div className="score-grid">{metrics.map(row=><article key={row[0]}><span>{row[0]}</span><strong>{row[1]}</strong><small>{row[2]}</small></article>)}</div></section>
    <div className="privacy-strip"><LockKeyhole/><span><strong>Privacy-safe analytics boundary</strong><small>Only pseudonymous IDs and categorical events leave the application. Amounts, account names, transaction text, prompts, and personal data remain excluded.</small></span><em>Enforced</em></div>
  </div>
}
