import React, { useState } from "react";
import { Activity, AlertTriangle, ArrowRight, Building2, Check, CheckCircle2, ChevronRight, Clock3, Eye, FileCheck2, Filter, KeyRound, LockKeyhole, MessageSquareText, Search, ShieldCheck, Sparkles, UserCheck, Users } from "lucide-react";
import "./platform.css";

const households = [
  { name:"Taylor Family", advisor:"Morgan Lee", status:"Review ready", opportunity:"High-cost debt", updated:"12 min ago", tone:"ready", score:88 },
  { name:"Ortiz Household", advisor:"Morgan Lee", status:"Needs attention", opportunity:"Reserve coverage", updated:"2 hr ago", tone:"attention", score:64 },
  { name:"Chen Family", advisor:"Avery Kim", status:"Waiting on client", opportunity:"Account refresh", updated:"Yesterday", tone:"waiting", score:76 },
  { name:"Williams Household", advisor:"Avery Kim", status:"Review ready", opportunity:"Tax reserve", updated:"Yesterday", tone:"ready", score:91 },
];
const roleMatrix = [
  ["Firm owner","Firm administration, billing, policies, and all assigned households","2 users"],
  ["Advisor","Assigned households, analysis review, and client presentation","5 users"],
  ["Associate","Draft preparation; no final client approval","3 users"],
  ["Client owner","Household data, members, acknowledgments, and shared analyses","24 users"],
  ["Household member","Views explicitly permitted by the client owner","18 users"],
];
const events = [
  ["Morgan Lee","Approved an opportunity analysis","Taylor Family · High-cost debt","12 min ago"],
  ["Jordan Taylor","Acknowledged the educational-use disclosure","Taylor Family · Investment capacity","18 min ago"],
  ["System","Recalculated household metrics","Taylor Family · 42 verified inputs","22 min ago"],
];

function Intro({eyebrow,title,text,right}) { return <div className="platform-intro"><div><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{right}</div>; }
function Stat({label,value,note,tone=""}) { return <article className={`platform-stat ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }
function Heading({eyebrow,title,action}) { return <div className="platform-heading"><div><span>{eyebrow}</span><h2>{title}</h2></div>{action}</div>; }

export function AdvisorConsole() {
  const [selected,setSelected]=useState(households[0]);
  return <div className="platform-view"><Intro eyebrow="Advisor operating console" title="Start with the households that need judgment." text="Review system-detected opportunities, prepare client conversations, and preserve a defensible approval trail." right={<button className="platform-primary"><Users/> Add household</button>}/>
    <div className="platform-stats"><Stat label="Households" value="24" note="18 active this month"/><Stat label="Reviews ready" value="7" note="3 newly calculated" tone="good"/><Stat label="Needs attention" value="4" note="Data or cash-flow exceptions" tone="warn"/><Stat label="Awaiting client" value="5" note="Requests or acknowledgments"/></div>
    <section className="console-grid"><article className="platform-card"><Heading eyebrow="Client book" title="Household work queue" action={<div className="platform-tools"><button><Filter/></button><label><Search/><input placeholder="Search households"/></label></div>}/><div className="client-table"><div className="client-head"><span>Household</span><span>Status</span><span>Opportunity</span><span>Updated</span><span/></div>{households.map(row=><button className={selected.name===row.name?"selected":""} onClick={()=>setSelected(row)} key={row.name}><span><i>{row.name.split(" ").map(v=>v[0]).join("").slice(0,2)}</i><b>{row.name}<small>{row.advisor}</small></b></span><em className={row.tone}>{row.status}</em><span>{row.opportunity}</span><span>{row.updated}</span><ChevronRight/></button>)}</div></article>
      <article className="platform-card review-card"><span>Selected household</span><h2>{selected.name}</h2><small>Assigned to {selected.advisor}</small><div className="readiness"><strong>{selected.score}</strong><span>Financial system readiness</span></div><div className="opportunity-box"><span><Sparkles/> Opportunity awaiting review</span><strong>{selected.opportunity}</strong><p>The system found a planning condition that may warrant discussion. Review its inputs, assumptions, and educational framing before sharing.</p><button>Open review workspace <ArrowRight/></button></div><div className="review-buttons"><button><MessageSquareText/> Prepare meeting agenda</button><button><FileCheck2/> Request client information</button></div></article></section>
    <section className="platform-card activity-card"><Heading eyebrow="Audit stream" title="Recent firm activity" action={<button className="platform-link">View full audit log</button>}/>{events.map((row,index)=><div className="activity-row" key={index}><i><Activity/></i><span><strong>{row[0]}</strong> {row[1]}<small>{row[2]}</small></span><time>{row[3]}</time></div>)}</section>
  </div>;
}

export function AccessControl() {
  return <div className="platform-view"><Intro eyebrow="Firm & household access" title="Every person sees only what their role requires." text="Firm boundaries, household assignments, and sensitive actions are explicit, reviewable, and recorded." right={<button className="platform-primary"><UserCheck/> Invite user</button>}/>
    <div className="security-banner"><ShieldCheck/><span><strong>Northstar Advisory · isolated firm workspace</strong><small>24 households · 10 firm users · MFA policy enforced</small></span><em>All controls healthy</em></div>
    <section className="access-grid"><article className="platform-card"><Heading eyebrow="Tenant boundary" title="Organization structure"/><div className="tenant-tree"><div><i><Building2/></i><span><strong>Northstar Advisory</strong><small>Firm tenant · FCC-ORG-1048</small></span><b>Owner</b></div><section><div><i><Users/></i><span><strong>Advisory team</strong><small>10 members · 3 firm roles</small></span></div><div><i><LockKeyhole/></i><span><strong>24 client households</strong><small>Strictly isolated data spaces</small></span></div><div className="house-node"><i>TF</i><span><strong>Taylor Family</strong><small>2 members · Morgan Lee assigned</small></span><b>Client owner</b></div></section></div></article>
      <article className="platform-card"><Heading eyebrow="Security policies" title="Access requirements"/>{[["Multi-factor authentication","Required for all firm users"],["Advisor household assignment","Required before access"],["Sensitive export approval","Firm owner approval"],["Session timeout","30 minutes"],["Client data download","Disabled for associates"]].map(row=><div className="policy-row" key={row[0]}><i><Check/></i><span><strong>{row[0]}</strong><small>{row[1]}</small></span><em>Enforced</em></div>)}</article></section>
    <section className="platform-card role-card"><Heading eyebrow="Least-privilege roles" title="Role and permission model" action={<button className="platform-link">Manage custom roles</button>}/><div className="role-head"><span>Role</span><span>Effective access</span><span>Assigned</span><span/></div>{roleMatrix.map(row=><div className="role-row" key={row[0]}><strong>{row[0]}</strong><span>{row[1]}</span><b>{row[2]}</b><ChevronRight/></div>)}</section>
    <section className="platform-card audit-card"><Heading eyebrow="Security audit" title="Recent access events"/>{[["Morgan Lee","Viewed Taylor Family cash-flow analysis","Assigned advisor","10:42 AM",false],["Jordan Taylor","Viewed investment-capacity opportunity","Disclosure acknowledged","10:36 AM",false],["Avery Kim","Requested Williams Household export","Owner approval required","Yesterday",true]].map((row,index)=><div key={index}><i className={row[4]?"warn":""}>{row[4]?<AlertTriangle/>:<CheckCircle2/>}</i><span><strong>{row[0]}</strong><small>{row[1]}</small></span><em>{row[2]}</em><time>{row[3]}</time></div>)}</section>
  </div>;
}

export function AIGovernance() {
  const [traceOpen,setTraceOpen]=useState(true);
  return <div className="platform-view"><Intro eyebrow="Controlled intelligence" title="The system calculates. AI explains. A human decides." text="Every opportunity preserves its inputs, formula, assumptions, language policy, review state, and client acknowledgment." right={<span className="model-status"><i/> Policy engine active</span>}/>
    <section className="governance-flow">{[["Calculate","Deterministic engine","done"],["Explain","Constrained framing","done"],["Advisor review","Human judgment","current"],["Present","Approved + acknowledged",""]].map((row,index)=><React.Fragment key={row[0]}><article className={row[2]}><i>{index+1}</i><span><strong>{row[0]}</strong><small>{row[1]}</small></span>{row[2]==="done"?<CheckCircle2/>:row[2]==="current"?<Clock3/>:<LockKeyhole/>}</article>{index<3&&<ChevronRight/>}</React.Fragment>)}</section>
    <section className="governance-grid"><article className="platform-card analysis-review"><div className="analysis-title"><div><span><Sparkles/> Opportunity draft</span><h2>High-cost debt may be constraining deployable cash flow</h2><p>Taylor Family · Generated 10:31 AM · Policy FCC-OPP-2.1</p></div><em>Awaiting advisor review</em></div><div className="language-check"><ShieldCheck/><span><strong>Language policy passed</strong><small>Conditional educational framing; no instruction to transact, guarantee, product recommendation, or claim of optimality.</small></span><button>View checks</button></div><div className="draft-copy"><span>Client-ready draft</span><p>The household’s revolving card balance carries a materially higher rate than its other tracked liabilities. This may be an area to discuss when comparing liquidity needs, debt reduction, and additional investing. Several allocation scenarios are available for review.</p></div><div className="analysis-actions"><button className="return">Return for revision</button><button>Edit explanation</button><button className="approve"><Check/> Approve for client</button></div></article>
      <article className="platform-card trace-card"><button onClick={()=>setTraceOpen(!traceOpen)}><span><strong>Calculation provenance</strong><small>Verified inputs and formula</small></span><ChevronRight className={traceOpen?"open":""}/></button>{traceOpen&&<div>{[["Revolving balance","$8,400","AMEX · refreshed Aug 27"],["Annual percentage rate","20.90%","Client-confirmed assumption"],["Liquid reserves","$82,450","3 connected accounts"],["Reserve floor","$61,200","4.0 × essential spending"]].map(row=><section key={row[0]}><span>{row[0]}</span><strong>{row[1]}</strong><small>{row[2]}</small></section>)}<pre>{"rate_gap = 20.90% − 7.00% model return\navailable_above_floor = $21,250\nsignal = HIGH_COST_DEBT_REVIEW"}</pre><button><Eye/> Inspect all 42 inputs</button></div>}</article></section>
    <section className="platform-card evaluation-card"><Heading eyebrow="Model quality" title="Release evaluation suite" action={<span className="eval-pass"><CheckCircle2/> 148 / 150 passed</span>}/><div className="eval-grid"><Stat label="Calculation fidelity" value="100%" note="46 deterministic cases" tone="good"/><Stat label="Tenant isolation" value="100%" note="32 adversarial cases" tone="good"/><Stat label="Advice-language policy" value="98.6%" note="2 blocked for review" tone="warn"/><Stat label="Citation completeness" value="100%" note="24 household cases" tone="good"/></div><div className="blocked-note"><AlertTriangle/><span><strong>Two outputs blocked from client presentation</strong><small>Language implied a single optimal action. Both remain quarantined for policy review.</small></span><button>Review blocked cases <ArrowRight/></button></div></section>
  </div>;
}
